# Dockerfile for Pipenv wrapper
# Unfortunately it seems not possible to reuse the Django Dockerfile, as not installing any packages in it
# will result in all .build-deps apks being deleted from it and pipenv failing to lock/install
# The build steps of this file are taken from the Django Dockerfile to make the build a bit faster though.

FROM python:3.6-alpine3.8

ENV PIPENV_PYUP_API_KEY=""

VOLUME /src
WORKDIR /src

# Install bash, libpq and gettext
RUN apk add --no-cache bash gettext libpq

# Copy Python requirements dir and Install requirements
RUN pip install -U pipenv==2018.11.26 pip setuptools wheel
