# Development Dockerfile for Django app. Keep the first commands in sync with Dockerfile-poetry

FROM python:3.8-slim-buster

ENV POETRY_VIRTUALENVS_CREATE 0

# Install system requirements
RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential gettext libpq-dev zlib1g-dev libjpeg62-turbo-dev && \
    rm -rf /var/lib/apt/lists/*

# Copy Python requirements dir and Install requirements
RUN pip install -U pip setuptools wheel poetry

COPY ./wait-for-it.sh /usr/bin/

COPY pyproject.toml /
COPY poetry.lock /


# Install all dependencies from poetry.lock (dev included by default)
RUN poetry install

# Set the default directory where CMD will execute
WORKDIR /app

# Run Django's runserver by default
CMD python manage.py runserver 0.0.0.0:80
