# Dockerfile for Poetry wrapper
# The first build steps of this file are identical to those in the Django Dockerfile to make the build a bit faster.

FROM python:3.8-slim-buster

ENV POETRY_VIRTUALENVS_CREATE 0

# Use non-interactive frontend for debconf
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# Install system requirements
RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential gettext libpq-dev zlib1g-dev libjpeg62-turbo-dev && \
    rm -rf /var/lib/apt/lists/*

# Copy Python requirements dir and Install requirements
RUN pip install -U pip setuptools wheel poetry

VOLUME /src
WORKDIR /src
