# Generated by Django 2.2.24 on 2021-11-04 20:07

from django.db import migrations


def generate_eflows_config(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    BioPeriod = apps.get_model("stations", "BioPeriod")
    bioperiods = BioPeriod(
        name="Bioperiods",
        January=1,
        February=1,
        March=2,
        April=2,
        May=2,
        June=2,
        July=3,
        August=3,
        September=3,
        October=4,
        November=4,
        December=4,
    )
    bioperiods.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_eflows_config),
    ]
