# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-18 15:18
from __future__ import unicode_literals

from django.core.files import File
from django.db import migrations

import pandas as pd


def populate_stations(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Station = apps.get_model("stations", "Station")
    FET = apps.get_model("stations", "FET")
    meta_file_path = "static/Stations_Metadata.xlsx"
    station_meta_df = pd.read_excel(meta_file_path)

    fet3 = FET.objects.filter(fet_short_label="3").first()

    for idx, row in station_meta_df.iterrows():
        station_name = station_meta_df.loc[idx, "Station"]
        station_water_body = station_meta_df.loc[idx, "Water body"]
        station_latitude = float(station_meta_df.loc[idx, "Latitude"])
        station_longitude = float(station_meta_df.loc[idx, "Longitude"])
        station_catchment_area = float(station_meta_df.loc[idx, "DEM Watershed (Km2)"])
        station_hydro_file_name = station_meta_df.loc[idx, "File name"]

        station = Station(
            name=station_name,
            catchment_area=station_catchment_area,
            river_FET=fet3,
            longitude=station_longitude,
            latitude=station_latitude,
            river_body=station_water_body,
        )
        with open(f"static/measurements/{station_hydro_file_name}", "rb") as f:
            fbytes = File(f)
            station.hydrological_data.save(station_hydro_file_name, fbytes)

        station.save()


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0002_auto_20200218_1516"),
    ]

    operations = [
        migrations.RunPython(populate_stations),
    ]
