# Generated by Django 2.2.24 on 2021-11-04 20:07

from django.core.files import File
from django.db import migrations

import pandas as pd


def populate_stations(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Station = apps.get_model("stations", "Station")
    Bioperiod = apps.get_model("stations", "Bioperiod")
    meta_file_path = "static/Stations_Metadata.xlsx"
    station_meta_df = pd.read_excel(meta_file_path, engine="openpyxl")

    # Use pre-created bioperiod months
    bioperiod_months = Bioperiod.objects.filter(name="Bioperiods").first()

    for idx, row in station_meta_df.iterrows():
        station_name = station_meta_df.loc[idx, "Station"]
        station_water_body = station_meta_df.loc[idx, "Water body"]
        station_latitude = float(station_meta_df.loc[idx, "Latitude"])
        station_longitude = float(station_meta_df.loc[idx, "Longitude"])
        station_watershed_area = float(station_meta_df.loc[idx, "DEM Watershed (Km2)"])
        station_hydro_file_name = station_meta_df.loc[idx, "File name"]

        station = Station(
            name=station_name,
            watershed_area=station_watershed_area,
            bioperiods_months=bioperiod_months,
            longitude=station_longitude,
            latitude=station_latitude,
            river_body=station_water_body,
        )
        with open(f"static/measurements/{station_hydro_file_name}", "rb") as f:
            fbytes = File(f)
            station.hydrological_data.save(station_hydro_file_name, fbytes)

        station.save()


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0002_auto_20211104_2007"),
    ]

    operations = [
        migrations.RunPython(populate_stations),
    ]
